version: "2"

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    - ireturn
    - loggercheck
    - makezero
    - mirror
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - sloglint
    - staticcheck
    - tagalign
    - tagliatelle
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - wrapcheck
    - wsl_v5
  disable:
    - whitespace
  settings:
    cyclop:
      max-complexity: 15
    gocritic:
      enable-all: true
      disabled-checks:
        - tooManyResultsChecker
        - unnamedResult
    modernize:
      disable:
        - any
    nlreturn:
      block-size: 4
    whitespace:
      multi-func: true
      multi-if: true
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: true
      branch-max-lines: 5
      case-max-lines: 5
      cuddle-max-statements: 2
      default: all
      disable:
        - assign-exclusive
        - leading-whitespace
        - trailing-whitespace

formatters:
  enable:
    - gci
    - gofmt
#    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 200
