version: "2"

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
#    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
#    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godox
    - gomoddirectives
    - goprintffuncname
#    - gosec
    - govet
    - grouper
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 15
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: true
      branch-max-lines: 5
      case-max-lines: 5
      cuddle-max-statements: 2
      disable:
        - leading-whitespace
        - trailing-whitespace

formatters:
  enable:
    - gci
    - gofmt
#    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 200
