// Code generated by rebuild-config.go. DO NOT EDIT.

package main

var LumoGraphs = map[string][]GraphConfig{
	"async": {
		{
			Title:  "MySQL replication lag",
			Groups: []string{"async"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "clamp_min(avg by (service_name) ( (max_over_time(mysql_slave_status_seconds_behind_master{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_slave_status_seconds_behind_master{service_name=~\"$service_name\"}[5m])) - (max_over_time(mysql_slave_status_sql_delay{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_slave_status_sql_delay{service_name=~\"$service_name\"}[5m])) ),0) or clamp_min(avg by (service_name) ( (max_over_time(mysql_slave_status_seconds_behind_source{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_slave_status_seconds_behind_source{service_name=~\"$service_name\"}[5m])) - (max_over_time(mysql_slave_status_sql_delay{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_slave_status_sql_delay{service_name=~\"$service_name\"}[5m])) ),0)",
				},
			},
		},
	},
	"aurora": {
		{
			Title:  "Amazon Aurora Transaction Commits",
			Groups: []string{"aurora"},
			Unit:   "ops",
			Series: []SeriesConfig{
				{
					Legend: "Number of Amazon Aurora Commits ",
					Expr:   "avg by (service_name) (rate(mysql_global_status_auroradb_commits{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_auroradb_commits{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Amazon Aurora Commit avg Latency",
					Expr:   "avg by (service_name) (rate(mysql_global_status_auroradb_commit_latency{service_name=~\"$service_name\"}[$interval])/(rate(mysql_global_status_auroradb_commits{service_name=~\"$service_name\"}[$interval]) > 0)) or avg by (service_name) (irate(mysql_global_status_auroradb_commit_latency{service_name=~\"$service_name\"}[5m])/(irate(mysql_global_status_auroradb_commits{service_name=~\"$service_name\"}[5m]) > 0))",
				},
			},
		},
		{
			Title:  "Amazon Aurora Load",
			Groups: []string{"aurora"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Write Transaction Commit Load",
					Expr:   "avg by (service_name) (rate(mysql_global_status_auroradb_commit_latency{service_name=~\"$service_name\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_commit_latency{service_name=~\"$service_name\"}[5m])/1000000)",
				},
				{
					Legend: "DDL Load",
					Expr:   "avg by (service_name) (rate(mysql_global_status_auroradb_ddl_stmt_duration{service_name=~\"$service_name\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_ddl_stmt_duration{service_name=~\"$service_name\"}[5m])/1000000)",
				},
				{
					Legend: "SELECT load ",
					Expr:   "avg by (service_name) (rate(mysql_global_status_auroradb_select_stmt_duration{service_name=~\"$service_name\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_select_stmt_duration{service_name=~\"$service_name\"}[5m])/1000000)",
				},
				{
					Legend: "INSERT load",
					Expr:   "avg by (service_name) (rate(mysql_global_status_auroradb_insert_stmt_duration{service_name=~\"$service_name\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_insert_stmt_duration{service_name=~\"$service_name\"}[5m])/1000000)",
				},
				{
					Legend: "UPDATE load",
					Expr:   "avg by (service_name) (rate(mysql_global_status_auroradb_update_stmt_duration{service_name=~\"$service_name\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_update_stmt_duration{service_name=~\"$service_name\"}[5m])/1000000)",
				},
				{
					Legend: "DELETE load",
					Expr:   "avg by (service_name) (rate(mysql_global_status_auroradb_delete_stmt_duration{service_name=~\"$service_name\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_delete_stmt_duration{service_name=~\"$service_name\"}[5m])/1000000)",
				},
			},
		},
		{
			Title:  "Aurora Memory Used",
			Groups: []string{"aurora"},
			Unit:   "bytes",
			Series: []SeriesConfig{
				{
					Legend: "Aurora Lock Manager Memory",
					Expr:   "avg by (service_name) (max_over_time(mysql_global_status_aurora_lockmgr_memory_used{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_status_aurora_lockmgr_memory_used{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Aurora Dictionary Memory ",
					Expr:   "avg by (service_name) (max_over_time(mysql_global_status_aurora_dict_sys_mem_size{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_status_aurora_dict_sys_mem_size{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Amazon Aurora Statement Latency",
			Groups: []string{"aurora"},
			Unit:   "µs",
			Series: []SeriesConfig{
				{
					Legend: "DDL Latency",
					Expr:   "avg by (service_name) ((rate(mysql_global_status_auroradb_ddl_stmt_duration{service_name=~\"$service_name\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{service_name=~\"$service_name\",command=~'alter_table|create_index|drop_index|drop_table'}[$interval])) without(command))))",
				},
				{
					Legend: "SELECT Latency",
					Expr:   "avg by (service_name) ((rate(mysql_global_status_auroradb_select_stmt_duration{service_name=~\"$service_name\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{service_name=~\"$service_name\",command='select'}[$interval])) without(command))+rate(mysql_global_status_qcache_hits{service_name=~\"$service_name\"}[$interval])))",
				},
				{
					Legend: "INSERT Latency",
					Expr:   "avg by (service_name) ((rate(mysql_global_status_auroradb_insert_stmt_duration{service_name=~\"$service_name\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{service_name=~\"$service_name\",command=~'insert|insert_select'}[$interval])) without(command))))",
				},
				{
					Legend: "UPDATE Latency",
					Expr:   "avg by (service_name) ((rate(mysql_global_status_auroradb_update_stmt_duration{service_name=~\"$service_name\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{service_name=~\"$service_name\",command=~'update|update_multi'}[$interval])) without(command))))",
				},
				{
					Legend: "DELETE Latency",
					Expr:   "avg by (service_name) ((rate(mysql_global_status_auroradb_delete_stmt_duration{service_name=~\"$service_name\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{service_name=~\"$service_name\",command=~'delete|delete_multi'}[$interval])) without(command))))",
				},
			},
		},
		{
			Title:  "Amazon Aurora Special Command Counters",
			Groups: []string{"aurora"},
			Unit:   "ops",
			Series: []SeriesConfig{
				{
					Legend: "{{command}}",
					Expr:   "avg by (service_name) (rate(mysql_global_status_commands_total{service_name=~\"$service_name\",command=~'awslambda|alter_system|unit_test|show_volume_status'}[$interval]))",
				},
			},
		},
		{
			Title:  "Amazon Aurora Problems",
			Groups: []string{"aurora"},
			Unit:   "ops",
			Series: []SeriesConfig{
				{
					Legend: "Thread Deadlocks",
					Expr:   "avg by (service_name) (rate(mysql_global_status_auroradb_thread_deadlocks{service_name=~\"$service_name\"}[$interval]))",
				},
				{
					Legend: "Missing History on Replica Incidents",
					Expr:   "avg by (service_name) (rate(mysql_global_status_aurora_missing_history_on_replica_incidents{service_name=~\"$service_name\"}[$interval]))",
				},
				{
					Legend: "Reserved Mem Exceeded Incidents",
					Expr:   "avg by (service_name) (rate(mysql_global_status_aurora_reserved_mem_exceeded_incidents{service_name=~\"$service_name\"}[$interval]))",
				},
			},
		},
	},
	"gr": {
		{
			Title:  "Replication Lag",
			Groups: []string{"gr"},
			Unit:   "s",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "max by (service_name) (max_over_time(mysql_perf_schema_replication_group_worker_lag_in_seconds{replication_set=~\"$replication_set\"}[$interval]) or max_over_time(mysql_perf_schema_replication_group_worker_lag_in_seconds{replication_set=~\"$replication_set\"}[5m]))",
				},
			},
		},
		{
			Title:  "Replication Delay",
			Groups: []string{"gr"},
			Unit:   "s",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "max by (service_name) (max_over_time(mysql_perf_schema_replication_group_worker_rep_delay_seconds{replication_set=~\"$replication_set\"}[$interval]) or max_over_time(mysql_perf_schema_replication_group_worker_rep_delay_seconds{replication_set=~\"$replication_set\"}[5m]))  < 20202020",
				},
			},
		},
		{
			Title:  "Transactions in the Queue for Checking",
			Groups: []string{"gr"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "avg by (service_name) (mysql_perf_schema_transactions_in_queue{replication_set=~\"$replication_set\"} or mysql_perf_schema_5_transactions_in_queue{replication_set=~\"$replication_set\"})",
				},
			},
		},
	},
	"innodb": {
		{
			Title:  "InnoDB Row Reads",
			Groups: []string{"innodb"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Rows {{ operation }}",
					Expr:   "avg by (service_name) (rate(mysql_global_status_innodb_row_ops_total{service_name=~\"$service_name\",operation=\"read\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{service_name=~\"$service_name\",operation=\"read\"}[5m]))",
				},
			},
		},
		{
			Title:  "InnoDB Row Writes",
			Groups: []string{"innodb"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Rows {{ operation }}",
					Expr:   "avg by (service_name,operation) (rate(mysql_global_status_innodb_row_ops_total{service_name=~\"$service_name\",operation!=\"read\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{service_name=~\"$service_name\",operation!=\"read\"}[5m]))",
				},
			},
		},
		{
			Title:  "InnoDB Data I/O",
			Groups: []string{"innodb"},
			Unit:   "ops",
			Series: []SeriesConfig{
				{
					Legend: "Data Reads",
					Expr:   "avg by (service_name) (rate(mysql_global_status_innodb_data_reads{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_innodb_data_reads{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Data Writes",
					Expr:   "avg by (service_name) (rate(mysql_global_status_innodb_data_writes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_innodb_data_writes{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Data Total IOPS",
					Expr:   "avg by (service_name) ((rate(mysql_global_status_innodb_data_reads{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_innodb_data_reads{service_name=~\"$service_name\"}[5m]))+ (rate(mysql_global_status_innodb_data_writes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_innodb_data_writes{service_name=~\"$service_name\"}[5m])))",
				},
			},
		},
		{
			Title:  "InnoDB FSyncs",
			Groups: []string{"innodb"},
			Unit:   "ops",
			Series: []SeriesConfig{
				{
					Legend: "Data Fsyncs",
					Expr:   "avg by (service_name) (rate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Log Fsyncs",
					Expr:   "avg by (service_name) (rate(mysql_global_status_innodb_os_log_fsyncs{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "InnoDB Pending IO",
			Groups: []string{"innodb"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Pending Data Reads",
					Expr:   "avg by (service_name) (avg_over_time(mysql_global_status_innodb_data_pending_reads{service_name=~\"$service_name\"}[$interval]) or avg_over_time(mysql_global_status_innodb_data_pending_reads{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Pending Data Writes",
					Expr:   "avg by (service_name) (avg_over_time(mysql_global_status_innodb_data_pending_writes{service_name=~\"$service_name\"}[$interval]) or avg_over_time(mysql_global_status_innodb_data_pending_writes{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Pending Log Writes",
					Expr:   "avg by (service_name) (avg_over_time(mysql_global_status_innodb_os_log_pending_writes{service_name=~\"$service_name\"}[$interval]) or avg_over_time(mysql_global_status_innodb_os_log_pending_writes{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "InnoDB IO Targets Bandwidth",
			Groups: []string{"innodb"},
			Unit:   "Bps",
			Series: []SeriesConfig{
				{
					Legend: "{{event_name}} ",
					Expr:   "topk(10,sum(rate(mysql_perf_schema_file_events_bytes_total{service_name=~\"$service_name\", event_name=~\"wait/io/file/innodb.*\"}[$interval])) by (service_name,event_name))  or topk(10,sum(irate(mysql_perf_schema_file_events_bytes_total{service_name=~\"$service_name\", event_name=~\"wait/io/file/innodb.*\"}[5m])) by (service_name,event_name))  ",
				},
			},
		},
		{
			Title:  "InnoDB Buffer Pool Page Activity",
			Groups: []string{"innodb"},
			Unit:   "ops",
			Series: []SeriesConfig{
				{
					Legend: "Pages Created",
					Expr:   "avg by (service_name) (rate(mysql_global_status_innodb_pages_created{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_innodb_pages_created{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Pages Read",
					Expr:   "avg by (service_name) (rate(mysql_global_status_innodb_pages_read{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_innodb_pages_read{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Pages Written",
					Expr:   "avg by (service_name) (rate(mysql_global_status_innodb_pages_written{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_innodb_pages_written{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "InnoDB Buffer Pool Requests",
			Groups: []string{"innodb"},
			Unit:   "ops",
			Series: []SeriesConfig{
				{
					Legend: "Read Requests",
					Expr:   "avg by (service_name) (rate(mysql_global_status_innodb_buffer_pool_read_requests{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_requests{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Write Requests",
					Expr:   "avg by (service_name) (rate(mysql_global_status_innodb_buffer_pool_write_requests{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_write_requests{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "InnoDB Checkpoint Age",
			Groups: []string{"innodb"},
			Unit:   "bytes",
			Series: []SeriesConfig{
				{
					Legend: "Uncheckpointed Bytes",
					Expr:   "avg by (service_name) (max_over_time(mysql_global_status_innodb_checkpoint_age{service_name=~\"$service_name\"}[$interval]) or  max_over_time(mysql_global_status_innodb_checkpoint_age{service_name=~\"$service_name\"}[5m]) or max_over_time(mysql_info_schema_innodb_metrics_recovery_log_lsn_checkpoint_age_total{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_info_schema_innodb_metrics_recovery_log_lsn_checkpoint_age_total{service_name=~\"$service_name\"}[5m]) or max_over_time(mysql_info_schema_innodb_metrics_log_log_lsn_checkpoint_age{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_info_schema_innodb_metrics_log_log_lsn_checkpoint_age{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Max Checkpoint Age",
					Expr:   "avg by (service_name) (max_over_time(mysql_global_status_innodb_checkpoint_max_age{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_status_innodb_checkpoint_max_age{service_name=~\"$service_name\"}[5m]) or max_over_time(mysql_info_schema_innodb_metrics_recovery_log_max_modified_age_async{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_info_schema_innodb_metrics_recovery_log_max_modified_age_async{service_name=~\"$service_name\"}[5m]) or max_over_time(mysql_info_schema_innodb_metrics_log_log_max_modified_age_async{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_info_schema_innodb_metrics_log_log_max_modified_age_async{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "InnoDB Log File Usage Hourly",
			Groups: []string{"innodb"},
			Unit:   "bytes",
			Series: []SeriesConfig{
				{
					Legend: "Data Written to Log Files",
					Expr:   "avg by (service_name) (increase(mysql_global_status_innodb_os_log_written{service_name=~\"$service_name\"}[1h]))",
				},
				{
					Legend: "Total Size of InnoDB Log Files",
					Expr:   "(mysql_version_info{innodb_version=~\"8.[0-9].[3-9][0-9]\",service_name=~\"$service_name\"} != 1 and avg by (service_name) (mysql_global_variables_innodb_log_files_in_group{service_name=~\"$service_name\"} * mysql_global_variables_innodb_log_file_size{service_name=~\"$service_name\"}) ) or (avg by (service_name)(mysql_global_variables_innodb_redo_log_capacity{service_name=~\"$service_name\"}) unless (mysql_version_info{innodb_version=~\"8.[0-9].[3-9][0-9]\",service_name=~\"$service_name\"} == 1))",
				},
			},
		},
		{
			Title:  "InnoDB Row Lock Wait Activity",
			Groups: []string{"innodb"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Deadlocks",
					Expr:   "avg by (service_name) ((rate(mysql_global_status_innodb_deadlocks{service_name=~\"$service_name\"}[$interval]) or rate(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{service_name=~\"$service_name\"}[$interval])) or (irate(mysql_global_status_innodb_deadlocks{service_name=~\"$service_name\"}[5m]) or irate(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{service_name=~\"$service_name\"}[5m])))",
				},
				{
					Legend: "Lock Waits",
					Expr:   "avg by (service_name) (rate(mysql_global_status_innodb_row_lock_waits{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_innodb_row_lock_waits{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Lock Wait Timeouts",
					Expr:   "avg by (service_name) (rate(mysql_info_schema_innodb_metrics_lock_lock_timeouts_total{service_name=~\"$service_name\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_lock_lock_timeouts_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Transaction History",
			Groups: []string{"innodb"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Transaction History Length",
					Expr:   "avg by (service_name) ((max_over_time(mysql_global_status_innodb_history_list_length{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_status_innodb_history_list_length{service_name=~\"$service_name\"}[5m])) or (max_over_time(mysql_info_schema_innodb_metrics_transaction_trx_rseg_history_len{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_info_schema_innodb_metrics_transaction_trx_rseg_history_len{service_name=~\"$service_name\"}[5m])))",
				},
				{
					Legend: "Max Purge Lag",
					Expr:   "avg by (service_name) (mysql_global_variables_innodb_max_purge_lag{service_name=~\"$service_name\"})",
				},
			},
		},
		{
			Title:  "InnoDB AHI Usage",
			Groups: []string{"innodb"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "AHI - Total Searches",
					Expr:   "avg by (service_name) (rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{service_name=~\"$service_name\"}[$interval])+ rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{service_name=~\"$service_name\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{service_name=~\"$service_name\"}[5m])+ irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "AHI - Misses",
					Expr:   "avg by (service_name) (rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{service_name=~\"$service_name\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "InnoDB AHI Miss Ratio",
			Groups: []string{"innodb"},
			Unit:   "percentunit",
			Series: []SeriesConfig{
				{
					Legend: "AHI - Miss Ratio",
					Expr:   "avg by (service_name) (1-((rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{service_name=~\"$service_name\"}[$interval]))/(rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{service_name=~\"$service_name\"}[$interval])+rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{service_name=~\"$service_name\"}[$interval])) or(irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{service_name=~\"$service_name\"}[5m]))/(irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{service_name=~\"$service_name\"}[5m])+irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{service_name=~\"$service_name\"}[5m]))))",
				},
			},
		},
		{
			Title:  "InnoDB Contention - OS Waits",
			Groups: []string{"innodb"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "RW Locks S OS Waits",
					Expr:   "avg by (service_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_s_os_waits_total{service_name=~\"$service_name\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_s_os_waits_total{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "RW Locks SX OS Waits",
					Expr:   "avg by (service_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_sx_os_waits_total{service_name=~\"$service_name\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_sx_os_waits_total{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "RW Locks X OS Waits",
					Expr:   "avg by (service_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_x_os_waits_total{service_name=~\"$service_name\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_x_os_waits_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "InnoDB Contention - Spin Rounds",
			Groups: []string{"innodb"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "RW Locks S Spin Rounds",
					Expr:   "avg by (service_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_s_spin_rounds_total{service_name=~\"$service_name\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_s_spin_rounds_total{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "RW Locks SX Spin Rounds",
					Expr:   "avg by (service_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_sx_spin_rounds_total{service_name=~\"$service_name\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_sx_spin_rounds_total{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "RW Locks X Spin Rounds",
					Expr:   "avg by (service_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_x_spin_rounds_total{service_name=~\"$service_name\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_x_spin_rounds_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
	},
	"mongo": {
		{
			Title:  "Command Operations",
			Groups: []string{"mongo"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "repl_{{type}}",
					Expr:   "avg by (service_name, type) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[$interval]) or  irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[5m]) or rate(mongodb_mongos_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[$interval]) or  irate(mongodb_mongos_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[5m]))",
				},
				{
					Legend: "ttl_delete",
					Expr:   "avg by (service_name) (rate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[$interval]) or  irate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[5m]) or rate(mongodb_mongos_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[$interval]) or  irate(mongodb_mongos_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "{{legacy_op_type}}",
					Expr:   "avg by (legacy_op_type) (rate(mongodb_ss_opcounters{service_name=~\"$service_name\", legacy_op_type!=\"command\"}[$interval]) or irate(mongodb_ss_opcounters{service_name=~\"$service_name\", legacy_op_type!=\"command\"}[5m]))",
				},
			},
		},
		{
			Title:  "Latency Detail",
			Groups: []string{"mongo"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{type}}",
					Expr:   "avg by (service_name,type) (rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\"}[$interval]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\"}[5m]) > 0))",
				},
			},
		},
		{
			Title:  "Connections",
			Groups: []string{"mongo"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Connections",
					Expr:   "avg by (service_name) (mongodb_mongod_connections{service_name=~\"$service_name\", state=\"current\"} or mongodb_mongos_connections{service_name=~\"$service_name\", state=\"current\"} or mongodb_connections{service_name=~\"$service_name\", state=\"current\"})",
				},
			},
		},
		{
			Title:  "Cursors",
			Groups: []string{"mongo"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{state}}",
					Expr:   "avg by (service_name,state) (mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\"} or mongodb_mongod_cursors{service_name=~\"$service_name\"} or mongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\"} or  mongodb_mongos_cursors{service_name=~\"$service_name\"})",
				},
			},
		},
		{
			Title:  "Document Operations",
			Groups: []string{"mongo"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{state}}",
					Expr:   "avg by (service_name,state) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[$interval]) or  irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Queued Operations",
			Groups: []string{"mongo"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{type}}",
					Expr:   "avg by (service_name,type) (mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\"})",
				},
			},
		},
		{
			Title:  "Query Efficiency",
			Groups: []string{"mongo"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Document",
					Expr:   "sum(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval]))/ sum(rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[$interval]))  or sum(irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m]))/ sum(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[5m]))",
				},
				{
					Legend: "Index",
					Expr:   "(sum(rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[$interval]))/ sum(rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[$interval]))  or sum(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[5m]))/ sum(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[5m])))",
				},
			},
		},
		{
			Title:  "Scanned and Moved Objects",
			Groups: []string{"mongo"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{state}}",
					Expr:   "avg by (service_name) (rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\"}[$interval]) or  irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "moved",
					Expr:   "avg by (service_name) (rate(mongodb_mongod_metrics_record_moves_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
	},
	"mysql": {
		{
			Title:  "MySQL Connections",
			Groups: []string{"mysql"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Connections",
					Expr:   "avg by (service_name) (max(max_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[$interval]) or  max_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[5m])))",
				},
				{
					Legend: "Max Used Connections",
					Expr:   "avg by (service_name) (max_over_time(mysql_global_status_max_used_connections{service_name=~\"$service_name\"}[$interval]) or  max_over_time(mysql_global_status_max_used_connections{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Max Connections",
					Expr:   "avg by (service_name) (max_over_time(mysql_global_variables_max_connections{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_variables_max_connections{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "MySQL Aborted Connections",
			Groups: []string{"mysql"},
			Unit:   "ops",
			Series: []SeriesConfig{
				{
					Legend: "Aborted Connects (attempts)",
					Expr:   "avg by (service_name) (rate(mysql_global_status_aborted_connects{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_aborted_connects{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Aborted Clients (timeout)",
					Expr:   "avg by (service_name) (rate(mysql_global_status_aborted_clients{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_aborted_clients{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "MySQL Client Thread Activity",
			Groups: []string{"mysql"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Peak Threads Connected",
					Expr:   "avg by (service_name) (max_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Peak Threads Running",
					Expr:   "avg by (service_name) (max_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Avg Threads Running",
					Expr:   "avg by (service_name) (avg_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[$interval]) or  avg_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "MySQL Temporary Objects",
			Groups: []string{"mysql"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Created Tmp Tables",
					Expr:   "avg by (service_name) (rate(mysql_global_status_created_tmp_tables{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_created_tmp_tables{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Created Tmp Disk Tables",
					Expr:   "avg by (service_name) (rate(mysql_global_status_created_tmp_disk_tables{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_created_tmp_disk_tables{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Created Tmp Files",
					Expr:   "avg by (service_name) (rate(mysql_global_status_created_tmp_files{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_created_tmp_files{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "MySQL Select Types",
			Groups: []string{"mysql"},
			Unit:   "ops",
			Series: []SeriesConfig{
				{
					Legend: "Select Full Join",
					Expr:   "avg by (service_name) (rate(mysql_global_status_select_full_join{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_select_full_join{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Select Full Range Join",
					Expr:   "avg by (service_name) (rate(mysql_global_status_select_full_range_join{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_select_full_range_join{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Select Range",
					Expr:   "avg by (service_name) (rate(mysql_global_status_select_range{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_select_range{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Select Range Check",
					Expr:   "avg by (service_name) (rate(mysql_global_status_select_range_check{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_select_range_check{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Select Scan",
					Expr:   "avg by (service_name) (rate(mysql_global_status_select_scan{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_select_scan{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "MySQL Sorts",
			Groups: []string{"mysql"},
			Unit:   "ops",
			Series: []SeriesConfig{
				{
					Legend: "Sort Rows",
					Expr:   "avg by (service_name) (rate(mysql_global_status_sort_rows{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_sort_rows{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Sort Range",
					Expr:   "avg by (service_name) (rate(mysql_global_status_sort_range{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_sort_range{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Sort Merge Passes",
					Expr:   "avg by (service_name) (rate(mysql_global_status_sort_merge_passes{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_sort_merge_passes{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Sort Scan",
					Expr:   "avg by (service_name) (rate(mysql_global_status_sort_scan{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_sort_scan{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "MySQL Questions",
			Groups: []string{"mysql"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Questions",
					Expr:   "avg by (service_name) (rate(mysql_global_status_questions{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_questions{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Top Command Counters",
			Groups: []string{"mysql"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Com_{{ command }}",
					Expr:   "topk(5, avg by (service_name,command) (rate(mysql_global_status_commands_total{service_name=~\"$service_name\"}[$interval])>0 or  irate(mysql_global_status_commands_total{service_name=~\"$service_name\"}[5m])>0))",
				},
			},
		},
		{
			Title:  "MySQL Handlers",
			Groups: []string{"mysql"},
			Unit:   "ops",
			Series: []SeriesConfig{
				{
					Legend: "{{ handler }}",
					Expr:   "avg by (service_name,handler) (rate(mysql_global_status_handlers_total{service_name=~\"$service_name\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or  irate(mysql_global_status_handlers_total{service_name=~\"$service_name\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m]))",
				},
			},
		},
		{
			Title:  "MySQL Query Cache Activity",
			Groups: []string{"mysql"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Hits",
					Expr:   "avg by (service_name) (rate(mysql_global_status_qcache_hits{node_name=\"$node_name\"}[$interval]) or irate(mysql_global_status_qcache_hits{node_name=\"$node_name\"}[5m]))",
				},
				{
					Legend: "Inserts",
					Expr:   "avg by (service_name) (rate(mysql_global_status_qcache_inserts{node_name=\"$node_name\"}[$interval]) or irate(mysql_global_status_qcache_inserts{node_name=\"$node_name\"}[5m]))",
				},
				{
					Legend: "Not Cached",
					Expr:   "avg by (service_name) (rate(mysql_global_status_qcache_not_cached{node_name=\"$node_name\"}[$interval]) or irate(mysql_global_status_qcache_not_cached{node_name=\"$node_name\"}[5m]))",
				},
				{
					Legend: "Prunes",
					Expr:   "avg by (service_name) (rate(mysql_global_status_qcache_lowmem_prunes{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_qcache_lowmem_prunes{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Queries in Cache",
					Expr:   "avg by (service_name) (max_over_time(mysql_global_status_qcache_queries_in_cache{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_status_qcache_queries_in_cache{service_name=~\"$service_name\"}[5m])) ",
				},
			},
		},
		{
			Title:  "MySQL Table Open Cache Status",
			Groups: []string{"mysql"},
			Unit:   "ops",
			Series: []SeriesConfig{
				{
					Legend: "Openings",
					Expr:   "avg by (service_name) (rate(mysql_global_status_opened_tables{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_opened_tables{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Hits",
					Expr:   "avg by (service_name) (rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Misses",
					Expr:   "avg by (service_name) (rate(mysql_global_status_table_open_cache_misses{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_table_open_cache_misses{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Misses due to Overflows",
					Expr:   "avg by (service_name) (rate(mysql_global_status_table_open_cache_overflows{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_table_open_cache_overflows{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Table Open Cache Hit Ratio",
					Expr:   "avg by (service_name) ((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[5m]))/ ((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[5m]))+ (rate(mysql_global_status_table_open_cache_misses{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_table_open_cache_misses{service_name=~\"$service_name\"}[5m]))))",
				},
			},
		},
		{
			Title:  "MySQL Open Tables",
			Groups: []string{"mysql"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Open Tables",
					Expr:   "avg by (service_name) (max_over_time(mysql_global_status_open_tables{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_status_open_tables{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Table Open Cache",
					Expr:   "avg by (service_name) (max_over_time(mysql_global_variables_table_open_cache{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_variables_table_open_cache{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "MySQL Table Definition Cache",
			Groups: []string{"mysql"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Open Table Definitions",
					Expr:   "avg by (service_name) (max_over_time(mysql_global_status_open_table_definitions{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_status_open_table_definitions{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Table Definitions Cache Size",
					Expr:   "avg by (service_name) (max_over_time(mysql_global_variables_table_definition_cache{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_variables_table_definition_cache{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Opened Table Definitions",
					Expr:   "avg by (service_name) (rate(mysql_global_status_opened_table_definitions{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_opened_table_definitions{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
	},
	"os": {
		{
			Title:  "CPU Usage",
			Groups: []string{"os"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{ mode }}",
					Expr:   "avg by (node_name,mode) (clamp_max(((avg by (mode,node_name) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=~\"user|system|wait|steal|irq|nice\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=~\"user|system|wait|steal|irq|nice\"}[5m]))),100))",
				},
				{
					Legend: "Max Core Utilization",
					Expr:   "clamp_max(max by (node_name) (sum  by (cpu,node_name) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
				},
			},
		},
		{
			Title:  "CPU Saturation and Max Core Usage",
			Groups: []string{"os"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Normalized CPU Load",
					Expr:   "avg by (node_name) ((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or (avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
				},
				{
					Legend: "Max CPU Core Utilization",
					Expr:   "clamp_max(max by (node_name) (sum  by (cpu,node_name) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
				},
				{
					Legend: "CPU Credits Usage",
					Expr:   "avg by (node_name) (aws_rds_cpu_credit_usage_average{node_name=~\"$node_name\"})",
				},
			},
		},
		{
			Title:  "Memory Utilization",
			Groups: []string{"os"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Free",
					Expr:   "avg by (node_name) (avg_over_time(node_memory_MemFree_bytes{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_memory_MemFree_bytes{node_name=~\"$node_name\"}[5m]))",
				},
				{
					Legend: "Buffers",
					Expr:   "avg by (node_name) (avg_over_time(node_memory_Buffers_bytes{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_memory_Buffers_bytes{node_name=~\"$node_name\"}[5m]))",
				},
				{
					Legend: "Used",
					Expr:   "clamp_min(avg by (node_name) (((avg_over_time(node_memory_MemTotal_bytes{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_memory_MemTotal_bytes{node_name=~\"$node_name\"}[5m])) - ((avg_over_time(node_memory_MemFree_bytes{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_memory_MemFree_bytes{node_name=~\"$node_name\"}[5m]))+  (avg_over_time(node_memory_Buffers_bytes{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_memory_Buffers_bytes{node_name=~\"$node_name\"}[5m])) +  (avg_over_time(node_memory_Cached_bytes{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_memory_Cached_bytes{node_name=~\"$node_name\"}[5m]))))),0)",
				},
				{
					Legend: "Cache",
					Expr:   "avg by (node_name) (avg(avg_over_time(node_memory_Cached_bytes{node_name=~\"$node_name\",job=~\"rds.*|node.*\"}[$interval]) or avg_over_time(node_memory_Cached_bytes{node_name=~\"$node_name\",job=~\"rds.*|node.*\"}[5m])) without (job))",
				},
				{
					Legend: "Total",
					Expr:   "avg by (node_name) (avg_over_time(node_memory_MemTotal_bytes{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_memory_MemTotal_bytes{node_name=~\"$node_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Swap Activity",
			Groups: []string{"os"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Swap In (Reads)",
					Expr:   "avg by (node_name) (rate(node_vmstat_pswpin{node_name=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=~\"$node_name\"}[5m]) * 4096)",
				},
				{
					Legend: "Swap Out (Writes)",
					Expr:   "avg by (node_name) (rate(node_vmstat_pswpout{node_name=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=~\"$node_name\"}[5m]) * 4096)",
				},
				{
					Legend: "Total",
					Expr:   "avg by (node_name) ((rate(node_vmstat_pswpin{node_name=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=~\"$node_name\"}[5m]) * 4096) + (rate(node_vmstat_pswpout{node_name=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=~\"$node_name\"}[5m]) * 4096))",
				},
			},
		},
		{
			Title:  "I/O Activity",
			Groups: []string{"os"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Disk Reads (Page In)",
					Expr:   "avg by (node_name) (rate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[5m]) * 1024 or (max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[5m])) * 1024)",
				},
				{
					Legend: "Disk Writes (Page Out)",
					Expr:   "avg by (node_name) ((rate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[5m]) * 1024) or (max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[5m])) * 1024)",
				},
				{
					Legend: "Total",
					Expr:   "avg by (node_name) ((rate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[5m]) * 1024) or ((max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[5m])) + (max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[5m])))* 1024)",
				},
			},
		},
		{
			Title:  "Disk IO Latency",
			Groups: []string{"os"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Read Latency",
					Expr:   "avg by (node_name) ((sum by (node_name) (rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval])) / sum by (node_name) (rate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval]) > 0 )) or (sum by (node_name) (irate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[5m])) /  sum by (node_name) (irate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[5m]) > 0 )) or avg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or avg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[5m])/1000 or avg_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[$interval])/1000 or avg_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[5m])/1000)",
				},
				{
					Legend: "Write Latency",
					Expr:   "avg by (node_name) ((sum by (node_name) (rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval])) / sum by (node_name) (rate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval]) > 0 )) or (sum by (node_name) (irate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[5m])) /  sum by (node_name) (irate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[5m]) > 0 )) or (avg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or avg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[5m])/1000) or (avg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[$interval]) or avg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[5m]))/1000)",
				},
				{
					Legend: "Avg Read Latency (1h)",
					Expr:   "avg by (node_name) ((sum by (node_name) (rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[1h])) / sum by (node_name) (rate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[1h]) > 0 )) or avg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[1h])/1000 or avg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[1h])/1000 or avg_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[1h])/1000 or avg_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[1h])/1000)",
				},
				{
					Legend: "Avg Write Latency (1h)",
					Expr:   "avg by (node_name) ((sum by (node_name) (rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[1h])) / sum by (node_name) (rate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[1h]) > 0 ))  or (avg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or avg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[1h])/1000) or (avg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[$interval])/1000 or avg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[1h])/1000))",
				},
			},
		},
		{
			Title:  "Network Traffic",
			Groups: []string{"os"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Inbound",
					Expr:   "sum by (node_name) (rate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or sum by (node_name) (irate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or sum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[$interval])) or sum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[5m])) ",
				},
				{
					Legend: "Outbound",
					Expr:   "sum by (node_name) (rate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or sum by (node_name) (irate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or sum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[$interval])) or sum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[5m]))",
				},
			},
		},
	},
	"pgsql": {
		{
			Title:  "Number of Locks",
			Groups: []string{"pgsql"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{mode}} - {{datname}}",
					Expr:   "avg by (service_name,datname,mode) (max_over_time(pg_locks_count{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\"}[$interval]) or max_over_time(pg_locks_count{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\"}[5m]))",
				},
			},
		},
		{
			Title:  "Tuples",
			Groups: []string{"pgsql"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Fetched",
					Expr:   "sum(rate(pg_stat_database_tup_fetched{datname=~\"$database\",instance=~\"$node_name\"}[$interval])) or  sum(irate(pg_stat_database_tup_fetched{datname=~\"$database\",instance=~\"$node_name\"}[5m]))",
				},
				{
					Legend: "Returned",
					Expr:   "sum(rate(pg_stat_database_tup_returned{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or sum(irate(pg_stat_database_tup_returned{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Inserted",
					Expr:   "sum(rate(pg_stat_database_tup_inserted{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or sum(irate(pg_stat_database_tup_inserted{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Updated",
					Expr:   "sum(rate(pg_stat_database_tup_updated{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or sum(irate(pg_stat_database_tup_updated{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Deleted",
					Expr:   "sum(rate(pg_stat_database_tup_deleted{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or sum(irate(pg_stat_database_tup_deleted{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Read Tuple Activity",
			Groups: []string{"pgsql"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Rows returned by queries",
					Expr:   "sum(rate(pg_stat_database_tup_returned{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or sum(irate(pg_stat_database_tup_returned{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Rows fetched by queries",
					Expr:   "sum(rate(pg_stat_database_tup_fetched{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or sum(irate(pg_stat_database_tup_fetched{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Tuples Changes by Queries",
			Groups: []string{"pgsql"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Rows inserted by queries",
					Expr:   "sum(rate(pg_stat_database_tup_inserted{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or sum(irate(pg_stat_database_tup_inserted{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Rows updated by queries",
					Expr:   "sum(rate(pg_stat_database_tup_updated{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or sum(irate(pg_stat_database_tup_updated{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Rows deleted by queries",
					Expr:   "sum(rate(pg_stat_database_tup_deleted{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or sum(irate(pg_stat_database_tup_deleted{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Transactions",
			Groups: []string{"pgsql"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Commits",
					Expr:   "sum(rate(pg_stat_database_xact_commit{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or  sum(irate(pg_stat_database_xact_commit{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Rollbacks",
					Expr:   "sum(rate(pg_stat_database_xact_rollback{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or sum(irate(pg_stat_database_xact_rollback{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Duration of Transactions",
			Groups: []string{"pgsql"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{state}}",
					Expr:   "avg by (service_name,state) (max_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service_name\"}[$interval]) or max_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Number of Temp Files",
			Groups: []string{"pgsql"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{datname}}",
					Expr:   "avg by (service_name,datname) (max_over_time(pg_stat_database_temp_files{service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\"}[$interval]) or  max_over_time(pg_stat_database_temp_files{service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\"}[5m]))",
				},
			},
		},
		{
			Title:  "Size of Temp Files",
			Groups: []string{"pgsql"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{datname}}",
					Expr:   "avg by (service_name,datname) (max_over_time(pg_stat_database_temp_bytes{service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\"}[$interval]) or  max_over_time(pg_stat_database_temp_bytes{service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\"}[5m]))",
				},
				{
					Legend: "increase {{datname}}",
					Expr:   "rate(pg_stat_database_temp_bytes{service_name=~\"$service_name\",datname!~\"|template(0|1)\"}[$interval]) or irate(pg_stat_database_temp_bytes{service_name=~\"$service_name\",datname!~\"|template(0|1)\"}[5m])",
				},
			},
		},
		{
			Title:  "Temp Files Activity",
			Groups: []string{"pgsql"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{datname}}",
					Expr:   "max by (service_name,datname) (increase(pg_stat_database_temp_files{service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\"}[$interval]))",
				},
			},
		},
		{
			Title:  "Temp Files Utilization",
			Groups: []string{"pgsql"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{datname}}",
					Expr:   "avg by (service_name,datname) (increase(pg_stat_database_temp_bytes{service_name=~\"$service_name\",datname=~\"$database\",datname!~\"|template(0|1)\"}[$interval]) or  increase(pg_stat_database_temp_bytes{service_name=~\"$service_name\",datname=~\"$database\",datname!~\"|template(0|1)\"}[5m]))",
				},
			},
		},
		{
			Title:  "Conflicts/Deadlocks",
			Groups: []string{"pgsql"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Deadlocks",
					Expr:   "sum(rate(pg_stat_database_deadlocks{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or  sum(irate(pg_stat_database_deadlocks{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Conflicts",
					Expr:   "sum(rate(pg_stat_database_conflicts{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or  sum(irate(pg_stat_database_conflicts{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Number of Locks",
			Groups: []string{"pgsql"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{mode}} - {{datname}}",
					Expr:   "avg by (service_name,datname,mode) (max_over_time(pg_locks_count{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\"}[$interval]) or max_over_time(pg_locks_count{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\"}[5m]))",
				},
			},
		},
	},
	"pxc": {
		{
			Title:  "Percona XtraDB / Galera Cluster Size",
			Groups: []string{"pxc"},
			Unit:   "short",
			Series: []SeriesConfig{
				{
					Legend: "Size",
					Expr:   "(min_over_time(mysql_global_status_wsrep_cluster_size[$interval]) or min_over_time(mysql_global_status_wsrep_cluster_size[5m])) *  on (service_name) group_left avg by (service_name) (mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"})",
				},
			},
		},
		{
			Title:  "Flow Control Paused Time",
			Groups: []string{"pxc"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{ service_name }}",
					Expr:   "clamp_max(avg by (service_name) ((rate(mysql_global_status_wsrep_flow_control_paused_ns[$interval]) or irate(mysql_global_status_wsrep_flow_control_paused_ns[5m])))/1000000000 * on (service_name) group_left avg by (service_name) (mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}),1)",
				},
			},
		},
		{
			Title:  "Flow Control Messages Sent",
			Groups: []string{"pxc"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{ service_name }}",
					Expr:   "(avg by (service_name) (rate(mysql_global_status_wsrep_flow_control_sent[$interval]) or irate(mysql_global_status_wsrep_flow_control_sent[5m]))) * on (service_name) group_left avg by (service_name) (mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"})",
				},
			},
		},
		{
			Title:  "Average Galera Replication Latency",
			Groups: []string{"pxc"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}} - Latency Average",
					Expr:   "avg by (service_name) (avg_over_time(mysql_galera_evs_repl_latency_avg_seconds[$interval])) * on (service_name) group_left avg by (service_name) (mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"})",
				},
			},
		},
		{
			Title:  "Galera Flow Control",
			Groups: []string{"pxc"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "FC Messages Received",
					Expr:   "avg by (service_name) (rate(mysql_global_status_wsrep_flow_control_recv{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_recv{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "FC Messages Sent",
					Expr:   "avg by (service_name) (rate(mysql_global_status_wsrep_flow_control_sent{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_sent{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Paused due to Flow Control",
					Expr:   "avg by (service_name) ((rate(mysql_global_status_wsrep_flow_control_paused_ns{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_paused_ns{service_name=~\"$service_name\"}[5m])))/1000000000",
				},
			},
		},
		{
			Title:  "Available Downtime before SST Required",
			Groups: []string{"pxc"},
			Unit:   "s",
			Series: []SeriesConfig{
				{
					Legend: "Time (1h avg)",
					Expr:   "avg by (service_name) (mysql_galera_gcache_size_bytes{service_name=~\"$service_name\"}) / ignoring(job) (avg by (service_name) (rate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service_name\"}[1h])+rate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service_name\"}[1h])))",
				},
				{
					Legend: "Time (Instant)",
					Expr:   "avg by (service_name) (mysql_galera_gcache_size_bytes{service_name=~\"$service_name\"}) / ignoring(job) (avg by (service_name) ((rate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service_name\"}[5m])) +  (rate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service_name\"}[5m]))))",
				},
			},
		},
		{
			Title:  "Galera Writeset Traffic",
			Groups: []string{"pxc"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Inbound",
					Expr:   "avg by (service_name) (rate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Outbound",
					Expr:   "avg by (service_name) (rate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
	},
	"replset": {
		{
			Title:  "Operation Latencies",
			Groups: []string{"replset"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{op_type}} - {{service_name}}",
					Expr:   "avg by (op_type,service_name) (rate(mongodb_ss_opLatencies_latency{service_name=~\"$service_name\"}[$interval]) / (rate(mongodb_ss_opLatencies_ops{service_name=~\"$service_name\"}[$interval]) > 0) or irate(mongodb_ss_opLatencies_latency{service_name=~\"$service_name\"}[5m]) / (irate(mongodb_ss_opLatencies_ops{service_name=~\"$service_name\"}[5m]) > 0))",
				},
			},
		},
		{
			Title:  "Reads & Writes",
			Groups: []string{"replset"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Active Readers - {{service_name}}",
					Expr:   "avg by(service_name) (mongodb_ss_globalLock_activeClients_readers{service_name=~\"$service_name\"})",
				},
				{
					Legend: "Active Writers - {{service_name}}",
					Expr:   "avg by(service_name) (mongodb_ss_globalLock_activeClients_writers{service_name=~\"$service_name\"})",
				},
				{
					Legend: "Queued Readers - {{service_name}}",
					Expr:   "avg by(service_name) (mongodb_ss_globalLock_currentQueue{service_name=~\"$service_name\",count_type=\"readers\"})",
				},
				{
					Legend: "Queued Writers - {{service_name}}",
					Expr:   "avg by(service_name) (mongodb_ss_globalLock_currentQueue{service_name=~\"$service_name\",count_type=\"writers\"})",
				},
			},
		},
		{
			Title:  "Average Connections",
			Groups: []string{"replset"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Current - {{service_name}}",
					Expr:   "avg by (service_name) (mongodb_ss_connections{service_name=~\"$service_name\",conn_type=~\"current\"})",
				},
				{
					Legend: "Available - {{service_name}}",
					Expr:   "avg by(service_name) (mongodb_ss_connections{service_name=~\"$service_name\",conn_type=~\"available\"})",
				},
				{
					Legend: "Idle - {{service_name}}",
					Expr:   "avg by(service_name) (mongodb_ss_connections{conn_type=~\"current\", service_name=~\"$service_name\"}) - avg by(service_name) (mongodb_ss_connections{conn_type=~\"active\", service_name=~\"$service_name\"})",
				},
			},
		},
		{
			Title:  "Replication Lag",
			Groups: []string{"replset"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "max_over_time(mongodb_mongod_replset_member_replication_lag{environment=~\".*\",cluster=~\"$cluster\",set=\"$rs_nm\",self=~\"|1\",service_name=~\"$secondary\"}[$interval]) > 0 ",
				},
			},
		},
		{
			Title:  "Oplog Recovery Window",
			Groups: []string{"replset"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{ service_name }}",
					Expr:   "mongodb_mongod_replset_oplog_head_timestamp{service_name=~\"$service_name\"}-mongodb_mongod_replset_oplog_tail_timestamp{service_name=~\"$service_name\"}",
				},
			},
		},
		{
			Title:  "Flow Control",
			Groups: []string{"replset"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "fc_count",
					Expr:   "max by ()(rate(mongodb_ss_flowControl_isLaggedCount{service_name=~\"$service_name\"}[$interval]))",
				},
				{
					Legend: "fc_time",
					Expr:   "max by ()(rate(mongodb_ss_flowControl_isLaggedTimeMicros{service_name=~\"$service_name\"}[$interval]))",
				},
			},
		},
		{
			Title:  "Oplog GB/Hour - $service_name",
			Groups: []string{"replset"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "sum(increase(mongodb_oplog_stats_wt_cache_bytes_written_from_cache{service_name=~\"$service_name\"}[1h]))",
				},
			},
		},
	},
	"sharding": {
		{
			Title:  "Command Operations",
			Groups: []string{"sharding"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "repl_{{legacy_op_type}}",
					Expr:   "sum by (environment, cluster, legacy_op_type) (rate(mongodb_ss_opcountersRepl{environment=~\".*\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\",legacy_op_type!~\"(command|query|getmore)\"}[$interval]))",
				},
				{
					Legend: "ttl_delete",
					Expr:   "sum by (environment, cluster) (rate(mongodb_ss_metrics_ttl_deletedDocuments{environment=~\".*\", rs_nm=~\"$set\",service_name=~\"$service_name\",cluster=~\"$cluster\"}[$interval]))",
				},
				{
					Legend: "{{legacy_op_type}}",
					Expr:   "sum by (environment, cluster, legacy_op_type) (rate(mongodb_ss_opcounters{environment=~\".*\", cluster=~\"$cluster\", rs_nm=~\"$set\",service_name=~\"$service_name\",legacy_op_type!=\"command\"}[$interval]))",
				},
			},
		},
		{
			Title:  "Operation Latencies",
			Groups: []string{"sharding"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{op_type}}",
					Expr:   "avg by (op_type) (rate(mongodb_ss_opLatencies_latency{environment=~\".*\", cluster=~\"$cluster\", service_name=~\"$service_name\"}[$interval]) / (rate(mongodb_ss_opLatencies_ops{environment=~\".*\", cluster=~\"$cluster\", service_name=~\"$service_name\"}[$interval]) > 0) or irate(mongodb_ss_opLatencies_latency{environment=~\".*\", cluster=~\"$cluster\",service_name=~\"$service_name\"}[5m]) / (irate(mongodb_ss_opLatencies_ops{environment=~\".*\", cluster=~\"$cluster\", service_name=~\"$service_name\"}[5m]) > 0))",
				},
			},
		},
		{
			Title:  "Operations Per Shard",
			Groups: []string{"sharding"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{set}}",
					Expr:   "sum(sum(rate(mongodb_op_counters_total{environment=~\".*\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\", type!=\"command\"}[$interval]) or  irate(mongodb_op_counters_total{environment=~\".*\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\", type!=\"command\"}[5m])) by (instance) * on (instance)  group_right mongodb_mongod_replset_my_state{environment=~\".*\", cluster=~\"$cluster\", set=~\"$set\", service_name=~\"$service_name\"} / mongodb_mongod_replset_my_state{environment=~\".*\", cluster=~\"$cluster\", set=~\"$set\", service_name=~\"$service_name\"}) by (set)",
				},
			},
		},
		{
			Title:  "Current Connections Per Shard",
			Groups: []string{"sharding"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{rs_nm}}",
					Expr:   "avg by (rs_nm) (mongodb_connections{environment=~\".*\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\", state=\"current\", rs_nm!=\"\"})",
				},
			},
		},
		{
			Title:  "Available Connections",
			Groups: []string{"sharding"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "sum by (set) (avg by (service_name,set) (mongodb_connections{environment=~\".*\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\", state=\"available\"}) * on (service_name) group_right avg by (service_name,set) (mongodb_mongod_replset_my_state{environment=~\".*\", cluster=~\"$cluster\", set=~\"$set\", service_name=~\"$service_name\"}/ mongodb_mongod_replset_my_state{cluster=\"$cluster\"}))",
				},
			},
		},
		{
			Title:  "Dynamic of Chunks",
			Groups: []string{"sharding"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{shard}}",
					Expr:   "avg by (shard) (rate(mongodb_mongos_sharding_shard_chunks_total{cluster=\"$cluster\"}[$interval]) or irate(mongodb_mongos_sharding_shard_chunks_total{cluster=\"$cluster\"}[5m]))",
				},
			},
		},
		{
			Title:  "Chunks Move Events",
			Groups: []string{"sharding"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{event}}",
					Expr:   "avg by (event) (rate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*moveChunk.*\"}[$interval]) or irate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*moveChunk.*\"}[5m]))",
				},
			},
		},
		{
			Title:  "Chunks Split Events",
			Groups: []string{"sharding"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{event}}",
					Expr:   "avg by (event) (rate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*split.*\"}[$interval]) or irate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*split.*\"}[5m]))",
				},
			},
		},
		{
			Title:  "Replication Lag by Shard",
			Groups: []string{"sharding"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "__auto",
					Expr:   "max by (set) (max(max_over_time(mongodb_mongod_replset_member_replication_lag{cluster=\"$cluster\",state!=\"ARBITER\"}[$interval])) by (service_name,set) or max(max_over_time(mongodb_mongod_replset_member_replication_lag{cluster=\"$cluster\",state!=\"ARBITER\"}[5m])) by (service_name,set))",
				},
			},
		},
		{
			Title:  "Oplog Range by Shard",
			Groups: []string{"sharding"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{set}}",
					Expr:   "max(max(mongodb_mongod_replset_oplog_head_timestamp{cluster=\"$cluster\"}-mongodb_mongod_replset_oplog_tail_timestamp{cluster=\"$cluster\"}) by (service_name) * on (service_name) group_right mongodb_mongod_replset_my_state{cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{cluster=\"$cluster\"}) by (set)",
				},
			},
		},
		{
			Title:  "Flow Control",
			Groups: []string{"sharding"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "fc_count",
					Expr:   "max by ()(rate(mongodb_ss_flowControl_isLaggedCount{service_name=~\"$service_name\"}[$interval]))",
				},
				{
					Legend: "fc_time",
					Expr:   "max by ()(rate(mongodb_ss_flowControl_isLaggedTimeMicros{service_name=~\"$service_name\"}[$interval]))",
				},
			},
		},
		{
			Title:  "Oplog GB/Hour - $service_name",
			Groups: []string{"sharding"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "sum(increase(mongodb_oplog_stats_wt_cache_bytes_written_from_cache{service_name=~\"$service_name\"}[1h]))",
				},
			},
		},
	},
	"valkey": {
		{
			Title:  "$service_name - Connected/Blocked Clients",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Connected - {{service_name}}",
					Expr:   "sum by(service_name)(redis_connected_clients{service_name=~\"$service_name\"})",
				},
				{
					Legend: "Blocked - {{service_name}}",
					Expr:   "sum by(service_name)(redis_blocked_clients{service_name=~\"$service_name\"})",
				},
			},
		},
		{
			Title:  "$service_name - Client Buffers",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Input",
					Expr:   "(rate(redis_client_recent_max_input_buffer_bytes{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Output",
					Expr:   "(rate(redis_client_recent_max_output_buffer_bytes{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "$service_name - Total Commands/Sec",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "sum by(service_name) (rate(redis_commands_total{service_name=~\"$service_name\"}[$__rate_interval]))",
				},
			},
		},
		{
			Title:  "$service_name - Read and Write Rate",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Reads - {{service_name}}",
					Expr:   "sum by(service_name) (rate(redis_total_reads_processed{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Writes - {{service_name}}",
					Expr:   "sum by(service_name) (rate(redis_total_writes_processed{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "$ns_service_name - Command by Type",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{cmd}} - {{ service_name}}",
					Expr:   "sum(rate(redis_commands_total{service_name=~\"$service_name\"} [1m])) by (service_name,cmd)",
				},
			},
		},
		{
			Title:  "$ns_service_name - Total Time Spent by Command/Sec",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{cmd}} - {{ service_name}}",
					Expr:   "sum by(cmd, service_name) (irate(redis_commands_duration_seconds_total{service_name=~\"$service_name\"}[1m])) != 0",
				},
			},
		},
		{
			Title:  "$node_name - Total Commands/Sec",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{node_name}}",
					Expr:   "sum by(service_name) (rate(redis_commands_total{service_name=~\"$service_name\"}[$__rate_interval]))",
				},
			},
		},
		{
			Title:  "$service_name - Read and Write Rate",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Reads - $service_name",
					Expr:   "sum by(service_name) (rate(redis_total_reads_processed{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Writes - $service_name",
					Expr:   "sum by(service_name) (rate(redis_total_writes_processed{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "$node_name - Commands by Type",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{cmd}} - {{service_name}}",
					Expr:   "sum(rate(redis_commands_total{service_name=~\"$service_name\"} [1m])) by (service_name,cmd)",
				},
			},
		},
		{
			Title:  "$node_name - Hits/Misses per Sec",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "hits - {{ service_name}}",
					Expr:   "irate(redis_keyspace_hits_total{service_name=~\"$service_name\"}[5m])",
				},
				{
					Legend: "misses - {{ service_name}}",
					Expr:   "irate(redis_keyspace_misses_total{service_name=~\"$service_name\"}[5m])",
				},
			},
		},
		{
			Title:  "IO thread Operations",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "reads - {{service_name}}",
					Expr:   "irate(redis_io_threaded_reads_processed{service_name=~\"$service_name\"}[5m])",
				},
				{
					Legend: "writes - {{service_name}}",
					Expr:   "irate(redis_io_threaded_writes_processed{service_name=~\"$service_name\"}[5m])",
				},
			},
		},
		{
			Title:  "IO Threads Active",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "redis_io_threads_active{service_name=~\"$service_name\"}",
				},
			},
		},
		{
			Title:  "Memory Usage",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "100 * (min by (service_name)(redis_memory_used_bytes{service_name=~\"$service_name\"})) / (min by (service_name)(redis_memory_max_bytes{service_name=~\"$service_name\"}) > 0 OR min by (service_name) (node_memory_MemTotal_bytes + on(node_name) group_left(service_name) redis_instance_info{service_name =~\"$service_name\"}))",
				},
			},
		},
		{
			Title:  "Total Memory Usage",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "used, {{ service_name}}",
					Expr:   "redis_memory_used_bytes{service_name=~\"$service_name\"}",
				},
				{
					Legend: "max, {{ service_name}}",
					Expr:   "redis_memory_max_bytes{service_name=~\"$service_name\"}",
				},
			},
		},
		{
			Title:  "Expired/Evicted Keys",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "expired, {{ service_name}}",
					Expr:   "sum(rate(redis_expired_keys_total{service_name=~\"$service_name\"}[5m])) by (service_name)",
				},
				{
					Legend: "evicted, {{ service_name}}",
					Expr:   "sum(rate(redis_evicted_keys_total{service_name=~\"$service_name\"}[5m])) by (service_name)",
				},
			},
		},
		{
			Title:  "Expiring vs Not-Expiring Keys",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "not expiring, {{ service_name}}",
					Expr:   "sum (redis_db_keys{service_name=~\"$service_name\"}) by (service_name) - sum (redis_db_keys_expiring{service_name=~\"$service_name\"}) by (service_name)",
				},
				{
					Legend: "expiring, {{ service_name }}",
					Expr:   "sum (redis_db_keys_expiring{service_name=~\"$service_name\"}) by (service_name)",
				},
			},
		},
		{
			Title:  "$service_name - Network Input",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "rate(redis_net_input_bytes_total{service_name=~\"$service_name\"}[$__interval]) or irate(redis_net_input_bytes_total{service_name=~\"$service_name\"}[5m])",
				},
			},
		},
		{
			Title:  "$service_name - Network Output",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "rate(redis_net_output_bytes_total{service_name=~\"$service_name\"}[$__interval]) or irate(redis_net_output_bytes_total{service_name=~\"$service_name\"}[5m])",
				},
			},
		},
		{
			Title:  "Total Memory Usage",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Used",
					Expr:   "sum(redis_memory_used_bytes{node_name=~\"$node_name\"})",
				},
				{
					Legend: "Max",
					Expr:   "sum(redis_memory_max_bytes{node_name=~\"$node_name\"})",
				},
			},
		},
		{
			Title:  "Cumulative Network I/O",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Input",
					Expr:   "sum(irate(redis_net_input_bytes_total{node_name=~\"$node_name\"}[$__rate_interval]))",
				},
				{
					Legend: "Output",
					Expr:   "sum(rate(redis_net_output_bytes_total{node_name=~\"$node_name\"}[$__rate_interval]))",
				},
			},
		},
		{
			Title:  "Base, Current, Last COW Size",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "redis_aof_base_size_bytes{service_name=~\"$service_name\",role=~\"primary\"}",
				},
				{
					Legend: "{{service_name}}",
					Expr:   "redis_aof_current_size_bytes{service_name=~\"$service_name\",role=~\"primary\"}",
				},
				{
					Legend: "{{service_name}}",
					Expr:   "redis_aof_last_cow_size_bytes{service_name=~\"$service_name\",role=~\"primary\"}",
				},
			},
		},
		{
			Title:  "Slowlog Length",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "redis_slowlog_length{service_name=~\"$service_name\"}",
				},
			},
		},
		{
			Title:  "Slowlog",
			Groups: []string{"valkey"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "__auto",
					Expr:   "sum by(service_name) (redis_slowlog_length{service_name=~\"$service_name\"})",
				},
			},
		},
	},
	"valkeycluster": {
		{
			Title:  "Slots Status",
			Groups: []string{"valkeycluster"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "ok - {{service_name}}",
					Expr:   "min by (service_name)(redis_cluster_slots_ok{service_name=~\"$service_name\"})",
				},
				{
					Legend: "fail - {{service_name}}",
					Expr:   "max by (service_name)(redis_cluster_slots_fail{service_name=~\"$service_name\"})",
				},
				{
					Legend: "pfail - {{service_name}}",
					Expr:   "max by (service_name)(redis_cluster_slots_pfail{service_name=~\"$service_name\"})",
				},
			},
		},
		{
			Title:  "$service_name - Cluster State",
			Groups: []string{"valkeycluster"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "min by (service_name)(redis_cluster_state{service_name=~\"$service_name\"})",
				},
			},
		},
		{
			Title:  "Cluster Messages",
			Groups: []string{"valkeycluster"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Sent - {{service_name}}",
					Expr:   "rate(redis_cluster_messages_sent_total{service_name=~\"$service_name\"}[$__rate_interval])",
				},
				{
					Legend: "Received - {{service_name}}",
					Expr:   "rate(redis_cluster_messages_received_total{service_name=~\"$service_name\"}[$__rate_interval])",
				},
			},
		},
		{
			Title:  "$service_name - Cluster Connections",
			Groups: []string{"valkeycluster"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "__auto",
					Expr:   "sum by(service_name) (redis_cluster_connections{service_name=~\"$service_name\"})",
				},
			},
		},
		{
			Title:  "$service_name - Known Nodes",
			Groups: []string{"valkeycluster"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}",
					Expr:   "redis_cluster_known_nodes{service_name=~\"$service_name\"}",
				},
			},
		},
	},
	"valkeyrepl": {
		{
			Title:  "$service_name - Replica vs Master Offsets",
			Groups: []string{"valkeyrepl"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}_{{slave_ip}}",
					Expr:   "redis_master_repl_offset{service_name=~\"$service_name\"} - on(service_name) group_left(slave_ip, slave_port) (redis_connected_slave_offset_bytes{service_name=~\"$service_name\"})",
				},
			},
		},
		{
			Title:  "Replicas",
			Groups: []string{"valkeyrepl"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "__auto",
					Expr:   "sum(redis_connected_slaves{node_name=~\"$node_name\", service_name=~\"$service_name\"})",
				},
			},
		},
		{
			Title:  "Replica Resync Info",
			Groups: []string{"valkeyrepl"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{service_name}}_full_resyncs",
					Expr:   "redis_replica_resyncs_full{node_name=~\"$node_name\", service_name=~\"$service_name\"}",
				},
				{
					Legend: "{{service_name}}_partial_resyncs",
					Expr:   "redis_replica_partial_resync_accepted{node_name=~\"$node_name\", service_name=~\"$service_name\"}",
				},
				{
					Legend: "{{service_name}}_partial_resync_denies",
					Expr:   "redis_replica_partial_resync_denied{node_name=~\"$node_name\", service_name=~\"$service_name\"}",
				},
			},
		},
	},
	"wiredtiger": {
		{
			Title:  "WiredTiger Transactions",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{type}}",
					Expr:   "avg by (service_name,type) (rate(mongodb_mongod_wiredtiger_transactions_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "WiredTiger Cache Activity",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Read into",
					Expr:   "avg by (service_name) (rate(mongodb_mongod_wiredtiger_cache_bytes_total{service_name=~\"$service_name\", type=\"read\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{service_name=~\"$service_name\", type=\"read\"}[5m]))",
				},
				{
					Legend: "Written from",
					Expr:   "avg by (service_name) (rate(mongodb_mongod_wiredtiger_cache_bytes_total{service_name=~\"$service_name\", type=\"written\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{service_name=~\"$service_name\", type=\"written\"}[5m]))",
				},
			},
		},
		{
			Title:  "WiredTiger Block Activity",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{type}}",
					Expr:   "avg by (service_name,type) (rate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "WiredTiger Sessions",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Cursors",
					Expr:   "avg by (service_name) (max_over_time(mongodb_mongod_wiredtiger_session_open_cursors_total{service_name=~\"$service_name\"}[$interval]) or max_over_time(mongodb_mongod_wiredtiger_session_open_cursors_total{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Sessions",
					Expr:   "avg by (service_name) (max_over_time(mongodb_mongod_wiredtiger_session_open_sessions_total{service_name=~\"$service_name\"}[$interval]) or max_over_time(mongodb_mongod_wiredtiger_session_open_sessions_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "WiredTiger Concurrency Tickets Available",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{txn_rw}}",
					Expr:   "avg by (service_name,txn_rw) ((max_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{service_name=~\"$service_name\"}[$interval]) or max_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{service_name=~\"$service_name\"}[5m])) - (max_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{service_name=~\"$service_name\"}[$interval]) or max_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{service_name=~\"$service_name\"}[5m])))",
				},
			},
		},
		{
			Title:  "Queued Operations",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{type}}",
					Expr:   "avg by (service_name,type) (max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\"}[$interval]) or max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "WiredTiger Checkpoint Time",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "current",
					Expr:   "avg by (service_name) (rate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "{{type}}",
					Expr:   "avg by (service_name,type) (max_over_time(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds{service_name=~\"$service_name\"}[$interval]) or max_over_time(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "WiredTiger Cache Eviction",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{type}}",
					Expr:   "avg by (service_name,type) (rate(mongodb_mongod_wiredtiger_cache_evicted_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_evicted_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "WiredTiger Cache Capacity",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Max",
					Expr:   "avg by (service_name) (max_over_time(mongodb_mongod_wiredtiger_cache_max_bytes{service_name=~\"$service_name\"}[$interval]) or max_over_time(mongodb_mongod_wiredtiger_cache_max_bytes{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "Used",
					Expr:   "avg by (service_name) (max_over_time(mongodb_mongod_wiredtiger_cache_bytes{service_name=~\"$service_name\", type=\"total\"}[$interval]) or max_over_time(mongodb_mongod_wiredtiger_cache_bytes{service_name=~\"$service_name\", type=\"total\"}[5m]))",
				},
			},
		},
		{
			Title:  "WiredTiger Cache Pages",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{type}}",
					Expr:   "avg by (service_name,type) (max_over_time(mongodb_mongod_wiredtiger_cache_pages{service_name=~\"$service_name\"}[$interval]) or max_over_time(mongodb_mongod_wiredtiger_cache_pages{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "WiredTiger Log Records",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{type}}",
					Expr:   "avg by (service_name,type) (rate(mongodb_mongod_wiredtiger_log_records_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_records_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Document Changes",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{state}}",
					Expr:   "avg by (service_name,state) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "repl_deleted",
					Expr:   "avg by (service_name) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"delete\"}[5m]))",
				},
				{
					Legend: "repl_updated",
					Expr:   "avg by (service_name) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"update\"}[5m]))",
				},
				{
					Legend: "repl_inserted",
					Expr:   "avg by (service_name) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"insert\"}[5m]))",
				},
				{
					Legend: "ttl_deleted",
					Expr:   "avg by (service_name) (rate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Scanned and Moved Objects",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "{{state}}",
					Expr:   "avg by (service_name,state) (rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\"}[5m]))",
				},
				{
					Legend: "moved",
					Expr:   "avg by (service_name) (rate(mongodb_mongod_metrics_record_moves_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
		{
			Title:  "Page Faults",
			Groups: []string{"wiredtiger"},
			Unit:   "",
			Series: []SeriesConfig{
				{
					Legend: "Faults",
					Expr:   "avg by (service_name) (rate(mongodb_mongod_extra_info_page_faults_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_extra_info_page_faults_total{service_name=~\"$service_name\"}[5m]) or rate(mongodb_extra_info_page_faults_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_extra_info_page_faults_total{service_name=~\"$service_name\"}[5m]))",
				},
			},
		},
	},
}
