name: Release Lumograph

on:
  pull_request:
    branches:
      - main

jobs:
  lint-prs:
    name: Lint Pull Requests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Run go-fmt and go-vet checks
        run: 
          go mod tidy && go fmt ./... && go vet ./...

      - name: Run golangci-lint checks
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          args: --timeout=5m
